# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Catalyst < Formula
  desc "Terminal UI tool to simplify triggering GitHub Actions workflows with matrix configurations"
  homepage "https://github.com/PraveenGongada/catalyst"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PraveenGongada/catalyst/releases/download/v1.1.1/catalyst_Darwin_x86_64.tar.gz"
      sha256 "d1ec1121d7bc57c729b86bfbacd83ef1385dfd824f36fab22fad22b4f592b0cc"

      def install
        bin.install "catalyst"

        # Install completion scripts if the command exists
        if Utils.safe_popen_read(bin/"catalyst", "-help").include?("completion")
          bash_output = Utils.safe_popen_read(bin/"catalyst", "completion", "bash") rescue ""
          (bash_completion/"catalyst").write bash_output unless bash_output.empty?

          zsh_output = Utils.safe_popen_read(bin/"catalyst", "completion", "zsh") rescue ""
          (zsh_completion/"_catalyst").write zsh_output unless zsh_output.empty?

          fish_output = Utils.safe_popen_read(bin/"catalyst", "completion", "fish") rescue ""
          (fish_completion/"catalyst.fish").write fish_output unless fish_output.empty?
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PraveenGongada/catalyst/releases/download/v1.1.1/catalyst_Darwin_arm64.tar.gz"
      sha256 "8243bcfe312bdef812e11cb8204b61bc7536184f6fa76fc9bbd77cb0e35f8dcb"

      def install
        bin.install "catalyst"

        # Install completion scripts if the command exists
        if Utils.safe_popen_read(bin/"catalyst", "-help").include?("completion")
          bash_output = Utils.safe_popen_read(bin/"catalyst", "completion", "bash") rescue ""
          (bash_completion/"catalyst").write bash_output unless bash_output.empty?

          zsh_output = Utils.safe_popen_read(bin/"catalyst", "completion", "zsh") rescue ""
          (zsh_completion/"_catalyst").write zsh_output unless zsh_output.empty?

          fish_output = Utils.safe_popen_read(bin/"catalyst", "completion", "fish") rescue ""
          (fish_completion/"catalyst.fish").write fish_output unless fish_output.empty?
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenGongada/catalyst/releases/download/v1.1.1/catalyst_Linux_x86_64.tar.gz"
      sha256 "ed1c70b14b9df2fb976569e68702f74c856b375ffa62ef5061cd45348b844fd6"
      def install
        bin.install "catalyst"

        # Install completion scripts if the command exists
        if Utils.safe_popen_read(bin/"catalyst", "-help").include?("completion")
          bash_output = Utils.safe_popen_read(bin/"catalyst", "completion", "bash") rescue ""
          (bash_completion/"catalyst").write bash_output unless bash_output.empty?

          zsh_output = Utils.safe_popen_read(bin/"catalyst", "completion", "zsh") rescue ""
          (zsh_completion/"_catalyst").write zsh_output unless zsh_output.empty?

          fish_output = Utils.safe_popen_read(bin/"catalyst", "completion", "fish") rescue ""
          (fish_completion/"catalyst.fish").write fish_output unless fish_output.empty?
        end
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/PraveenGongada/catalyst/releases/download/v1.1.1/catalyst_Linux_arm64.tar.gz"
      sha256 "7b681d948d77677171375b2f2fb6b9a63129c690e80b1e74e92f6d9d8ccf9703"
      def install
        bin.install "catalyst"

        # Install completion scripts if the command exists
        if Utils.safe_popen_read(bin/"catalyst", "-help").include?("completion")
          bash_output = Utils.safe_popen_read(bin/"catalyst", "completion", "bash") rescue ""
          (bash_completion/"catalyst").write bash_output unless bash_output.empty?

          zsh_output = Utils.safe_popen_read(bin/"catalyst", "completion", "zsh") rescue ""
          (zsh_completion/"_catalyst").write zsh_output unless zsh_output.empty?

          fish_output = Utils.safe_popen_read(bin/"catalyst", "completion", "fish") rescue ""
          (fish_completion/"catalyst.fish").write fish_output unless fish_output.empty?
        end
      end
    end
  end

  test do
    system "#{bin}/catalyst", "-version"
  end
end
